Add ID & version to type DatabaseModule
danitseitlin/redis-cloud-api-sdk pull request #157
Opened 2021-11-02 16:22 UTC by michaelk-redis

2021-11-02 22:39 UTC, danitseitlin requested changes

2021-11-02 22:39 UTC, danitseitlin commented on types/responses/general.ts
> +    version: string,
Please describe each new parameter

2021-11-03 07:52 UTC, michaelk-redis commented on types/responses/general.ts
> +    version: string,
done

2021-11-03 13:38 UTC, danitseitlin approved these changes

2021-11-03 13:38 UTC, merged